export const CONFIG = {
    GH_OAUTH_CLIENT_ID: process.env.GH_OAUTH_CLIENT_ID!,
    GH_OAUTH_CLIENT_SECRET: process.env.GH_OAUTH_CLIENT_SECRET!,
    GH_OAUTH_REDIRECT_URI: process.env.GH_OAUTH_REDIRECT_URI!,
    GH_OAUTH_STATE: process.env.GH_OAUTH_STATE!,
};